#!/bin/bash
head -n 11 | sort |tail +2 |cut -f1 | uniq -c | sort -nr | tr -s ' ' | cut -d ' ' -f3

tail -n +2 | cut -f1 | sort --ignore-case | uniq -c | sort --ignore-case -nr | head -11 | rev  | cut -d ' ' -f1 | rev
